### ISSUE TITLE
chui-shadow: glogi error using Clojurescript version 1.10.844

### ISSUE THREAD

**Issue by quesebifurcan** [lambdaisland/chui#14]
After upgrading to Clojurescript version 1.10.844, we started seeing this error when loading the browser runner in `chui-shadow`:

```
Failed to load lambdaisland/chui/shadow/browser_runner.cljs TypeError: G__52095.addHandler is not a function
    cljs$core$IFn$_invoke$arity$2 glogi.cljs:134
    cljs$core$IFn$_invoke$arity$2 glogi.cljs:156
    cljs$core$IFn$_invoke$arity$1 glogi.cljs:151
    lambdaisland$glogi$console$install_BANG_ console.cljs:81
```

Bumping glogi to to 1.0.100 as suggested here https://github.com/lambdaisland/glogi/issues/10 solved the issue for us.

```
$ clojure -Abrowser-test -Stree

lambdaisland/chui-shadow 1.0.173
  . lambdaisland/chui-ui 1.0.173
    . lambdaisland/chui-core 1.0.173
      X lambdaisland/glogi 1.0.70 :use-top
lambdaisland/glogi 1.0.100
```

Happy to make a PR to bump the glogi dependency in chui if you think it's a good idea?

**Comment by plexus** [comment]
Yes, please do. Unfortunately Google seems to have become more aggressive in making breaking changes, we'll have to update glogi to 1.0.100 everywhere to work with the latest ClojureScript.
