### ISSUE TITLE
"Run x tests" is disabled on first render

### ISSUE THREAD

**Issue by Valdermeyder** [lambdaisland/chui#17]
### Steps to reproduce
Open the page with tests

### Actual result
"Run x tests" is disabled
<img width="343" alt="Screenshot 2021-06-21 at 14 04 45" src="https://user-images.githubusercontent.com/5995043/122759134-e5132b00-d299-11eb-9918-5ab1a36980df.png">

### Expected result
"Run x tests" is enabled on the first render

### Workaround
Change input value or click any of search checkboxes

**Comment by humorless** [comment]
I close this issue given that it is already got solved by https://github.com/lambdaisland/chui/pull/22.
